import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nav } from "./nav";
import { Footer } from "./footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="relative bg-[url('/shoes_in_puddle.jpg')] bg-cover bg-center h-[700px] flex flex-col">
                    <div className="absolute inset-0 bg-gradient-to-t from-white to-transparent" />
                    <div className="relative">
                        <Nav />
                    </div>
                    <div className="relative flex-1">{children}</div>
                </div>
                <Footer />
            </body>
        </html>
    );
}
